### ISSUE TITLE
Recurse through #import in GQL files

### ISSUE THREAD

**Issue by amcvitty** [evenchange4/graphql.macro#35] opened 2018-10-04 01:47 UTC
I'm trying to upgrade our app to Create React App 2.0 right now and in the process switching from graphql-tag/loader (used with some custom config in react-app-rewired)

So our syntax changes from 
```javascript
import QUERY from "myquery.gql"
```
to 
```javascript
import { loader } from "graphql.macro";
const QUERY = loader("myquery.graphql")
```
So that's fine, but I'm noticing that the `#import` macro also doesn't work like in graphql-loader.

If I have 
```
myquery.gql:
#import "fields.gql"

query { 
  myobject {
    ...Fields
  }
}


fields.gql:
#import "subfields.gql"

fragment Fields on myobject {
  field1 { 
    ...SubFields
  }
} 

subfields.gql:

fragment SubFields on Field1 { 
   subfield1
   subfield2
}
```

The query that results is just 
```

fragment Fields on myobject {
  field1 {
    ...SubFields
  }
}

{
  myobject {
    ...Fields
  }
}
```

That is - it doesn't recurse and parse the imports in the file it's imporing to do that second level of importing. We have a few objects with nested references to other objects and to avoid duplicating the same common fields in those objects we make frequent use of this.

The workaround right now is to make sure all the nested fragments are explicitly imported in the query, which is not super hard, but it gets more tricky if you want to add an import in a fragment that is used in multiple queries because you have to find and update all those queries. In short, I preferred the graphql-loader implementation. 

So - is this a deliberate choice, or could this behaviour be added here?

**Comment by erictaylor** [comment] 2018-10-04 19:42
+1 to this issue. Having the same difficulty.

**Comment by smilexu** [comment] 2018-11-01 18:05
same issue for me

**Comment by bebbi** [comment] 2018-11-20 11:15
Referencing my issue posted in CRA as the cause is likely here.

**Comment by henrykuzmick** [comment] 2018-12-25 10:14
Same issue

**Comment by FezVrasta** [comment] 2019-05-16 19:29
@evenchange4 should we close this issue since it's fixed?

**Comment by evenchange4** [comment] 2019-05-17 06:47
Sure, close it. Please feel free to reopen this issue if the problem still occurs.

**Closed by evenchange4** 2019-05-17 06:47 UTC
